//search
GOLD_MAX = 2000000000,

//add after

#ifdef ENABLE_IKASHOP_RENEWAL
	OFFLINE_SHOP_NAME_MAX_LEN = 15 + CHARACTER_NAME_MAX_LEN +1,
	OFFLINESHOP_DURATION_MAX_MINUTES = 8 * 24 * 60,
	OFFLINESHOP_AUCTION_DURATION = 3 * 24 * 60,
	OFFLINESHOP_MAX_SEARCH_RESULT = 2500,
	OFFLINESHOP_SECONDS_PER_SEARCH = 5,
	OFFLINESHOP_SECONDS_PER_OFFER = 5,
	OFFLINESHOP_RESTORE_DURATION_COST = 1000000,
	OFFLINESHOP_MIN_OFFER_PERCENTAGE = 30,
	OFFLINESHOP_MAX_WEIGHT_PER_PLAYER = 2500,
	OFFLINESHOP_MAX_PENDING_OFFERS = 30,
	OFFLINESHOP_MAX_SAFEBOX_SIZE = 100,
#ifdef ENABLE_CHEQUE_SYSTEM
	YANG_PER_CHEQUE = 100000000,
#endif
#ifdef EXTEND_IKASHOP_PRO
	OFFLINESHOP_NOTIFICATION_FORMAT_LEN = 40,
#endif
#ifdef EXTEND_IKASHOP_ULTIMATE
	OFFLINESHOP_EXPIRING_SALE_HISTORY = 60*60*24*8, // 8 days
	OFFLINESHOP_SALE_HISTORY_COOLDOWN = 60*60*8, // 8 hours
	OFFSHOP_DECORATION_TIME = 15 * 24 * 60,
	OFFSHOP_LOCK_INDEX_INIT = 15*10, // first page unlocked by default
	OFFSHOP_SEARCH_PREMIUM_TIME = 15*24*60*60,
#endif
#endif

//search in function @ enum EWindows
	BELT_INVENTORY,
	GROUND,

//after add
#ifdef ENABLE_IKASHOP_RENEWAL
	IKASHOP_OFFLINESHOP,
	IKASHOP_SAFEBOX,
	IKASHOP_AUCTION,
#endif